title: Endrigo Antonini
description: Tecnologia, Informa&#231;&#227;o, Atualidade
url: https://blog.endrigoantonini.com.br
baseurl: ''
future: true

author:
  name: 'Endrigo Antonini'

paginate_path: 'page/:num/'
permalink: :year/:month/:day/:title/
timezone: America/Sao_Paulo

markdown: kramdown
highlighter: rouge
paginate: 10

include: [.htaccess]

plugins:
 # - jekyll-mentions
 - jemoji
 - jekyll-redirect-from

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: antonini
   twitter: antonini

# Custom vars
google_analytics: '367078566'
show_related_posts: true
disqus_shortname: endrigoantonini

ads:
  show_ads: true
  google:
    client: 'ca-pub-6910124936664106'
    slot: '2081252185'
