source 'https://rubygems.org'

#gem 'github-pages', '~> 31'
gem 'github-pages', group: :jekyll_plugins
gem 'jemoji'
gem 'rouge'
# gem 'jekyll-mentions'
gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-archives'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'

